spring:
  datasource:
    url: jdbc:mysql://8.210.20.126:3306/fm?serverTimezone=Asia/Shanghai
    username: fm
    password: JDPstEWnXMkfiny6
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:/mapper/*Mapping.xml
